In [2]:
import numpy as np
import time
import sys

In [8]:
l = range(1000)
print(sys.getsizeof(1000)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [12]:
SIZE = 100000000

l1 , l2 = range(SIZE),range(SIZE)
a1 , a2 = np.arange(SIZE) , np.arange(SIZE)

In [13]:
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("time taken by lists:",(time.time()-start)*1000)

start = time.time()
res = a1 + a2
print("time taken by numpy array:",(time.time()-start)*1000)

time taken by lists: 13231.330156326294
time taken by numpy array: 2761.67368888855


In [23]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)
# res.ndim
# array2d.ndim
array2d.dtype
array2d.itemsize

8

In [26]:
array2d.shape

(3, 3)

In [28]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.arange(2,5) # same as range
np.arange(2,10,2)
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [58]:
array2d = np.array([[1,2],[4,5],[7,8]])
# array2d.shape
array2d.reshape(6,1)
array2d.ravel()
array2d

array([[1, 2],
       [4, 5],
       [7, 8]])

In [62]:
# mathamatical function in np arrray
# array2d.min()
# array2d.max()
# array2d.sum()
# array2d
# array2d.sum(axis=0)
# array2d.sum(axis=1)
np.sqrt(array2d)
np.std(array2d)

2.5

In [69]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.cross(a,b)

array([-4, -4])

In [86]:
# indexing and slicing in numpy
a = np.array([6,7,8])
# a[0:2]
# a[-1]
a = np.array([[6,7,8],[1,2,3],[4,5,9]])
# a[0:2,2]
# a[-1,0:2]
# a[:,0:3]

# for row in a:
#     print(row)

# for cell in a.flat:
#     print(cell)

a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
# stacking them together 
print(np.vstack((a,b)))
print(np.hstack((a,b)))
#spilt hsplit and vsplit

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [99]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
# for cell in a.flatten():
#     print(cell)
# C and F are in row and fortan order # check flags in documentation for details of flags
for i in np.nditer(a,order='F',flags = ['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [101]:
# check op flags documentaion for op_flags in munpy
for i in np.nditer(a,op_flags = ['readwrite']):
    i[...] = i*i
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [103]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [105]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
